### ISSUE TITLE
Error while run test script

### ISSUE THREAD

**Issue by Volk95** [monosans/balaboba#2]
When I run test script from "Usage example" or script [test_balaboba.py](https://github.com/monosans/balaboba/blob/main/tests/test_balaboba.py) I recieve the next  error:

ImportError: cannot import name 'Balaboba' from 'balaboba' 

Please help, how I can resolve it?
 Thank you

**Comment by monosans** [comment]
https://github.com/monosans/balaboba#installation

**Comment by Volk95** [comment]
Thanks for reply. I installed according to the instruction and got the error. I'm new in python, please advise why the error had happened?

**Comment by Volk95** [comment]
> https://github.com/monosans/balaboba#installation

Thanks for reply. I installed according to the instruction and got the error. I'm new in python, please advise why the error had happened?

**Comment by monosans** [comment]
> I installed according to the instruction and got the error. I'm new in python, please advise why the error had happened?

Please make sure that you are using Python version 3.7 or higher.
